apiVersion: v1
kind: Template
labels:
  template: generic-java-tekton-pipeline
metadata:
  annotations:
    description: Application template for JWS applications built using a Tekton Pipeline
    version: 1.2.0
  name: generic-java-tekton-pipeline
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SA_NAME}
    namespace: ${NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${SA_NAME}_edit
    namespace: ${NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA_NAME}
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: ${APPLICATION_NAME}-git
    namespace: ${NAMESPACE}
  spec:
    type: git
    params:
    - name: url
      value: ${APPLICATION_SOURCE_REPO}
    - name: revision
      value: ${APPLICATION_SOURCE_REF}
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    name: maven-build
    namespace: ${NAMESPACE}
  spec:
    inputs:
      resources:
      - name: source
        type: git
    steps:   
    - name: package
      image: maven:3.6.0-jdk-8-slim
      workingDir: /workspace/source
      command:
      - /usr/bin/mvn
      args:
      - clean
      - package
      - install
      - -DskipTests
    - name: unit-tests
      image: maven:3.6.0-jdk-8-slim
      workingDir: /workspace/source
      command:
      - /usr/bin/mvn
      args:
      - test
    - name: native-integration-tests
      image: oracle/graalvm-ce:19.2.0.1
      workingDir: /workspace/source
      command:
      - /usr/bin/mvn
      args:
      - verify
      - -Pnative-image
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: ${APPLICATION_NAME}-pipeline
    namespace: ${NAMESPACE}
  spec:
    resources:
    - name: ${APPLICATION_NAME}-git
      type: git
    tasks:
    - name: maven-build
      taskRef: 
        name: maven-build
      resources:
        inputs:
        - name: source
          resource: ${APPLICATION_NAME}-git                             
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: quarkus-jwt-groups
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: basic-spring-boot
- description: Source code repo for demo app
  name: APPLICATION_SOURCE_REPO
  required: true
  value: https://github.com/cloudfirst-dev/quarkus-jwt-groups
- description: Source code branch for demo app
  name: APPLICATION_SOURCE_REF
  value: master
- description: Name of a service account that can deploy to this project
  name: SA_NAME
  required: true
  value: tekton